# Generated by Django 3.0.3 on 2020-08-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favorite_write',
            new_name='write',
        ),
    ]
