# Generated by Django 3.0.3 on 2020-08-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_auto_20200813_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='write',
            new_name='stockinfo',
        ),
    ]
