# Generated by Django 3.1 on 2020-08-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0004_auto_20200813_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
