# Generated by Django 3.1 on 2020-08-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0005_stockinfo_stock_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_lastprice',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
