# Generated by Django 3.1 on 2020-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0006_stockinfo_stock_lastprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'web_member',
            },
        ),
    ]
