# Generated by Django 3.1 on 2020-08-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0007_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpName', models.CharField(max_length=200)),
                ('corpCode', models.CharField(max_length=10)),
                ('corpCategory', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'web_member',
            },
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
