# Generated by Django 3.1 on 2020-08-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0008_auto_20200828_2113'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock_list',
            table='all_stock',
        ),
    ]
