# Generated by Django 3.1 on 2020-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0009_auto_20200828_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_list',
        ),
    ]
