# Generated by Django 3.1 on 2020-08-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0012_auto_20200828_2125'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='favorite',
        ),
    ]
