# Generated by Django 3.1 on 2020-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0013_auto_20200828_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
