# Generated by Django 3.1 on 2020-08-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0015_stock_list'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock_list',
            table='stock_list',
        ),
    ]
