# Generated by Django 3.1 on 2020-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0016_auto_20200829_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_startprice',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
