# Generated by Django 3.1 on 2020-09-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0017_stockinfo_stock_startprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_yesterdayprice',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
