# Generated by Django 3.1 on 2020-09-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0018_stockinfo_stock_yesterdayprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='stock_lastprice',
        ),
    ]
