# Generated by Django 3.1 on 2020-09-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0019_remove_stockinfo_stock_lastprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_lastprice',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
