# Generated by Django 3.1 on 2020-09-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0020_stockinfo_stock_lastprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='stock_gab',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='stock_gabwon',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
