# Generated by Django 3.1 on 2020-09-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0021_auto_20200908_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='stock_gab',
            field=models.FloatField(),
        ),
    ]
